import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';
import './global.css';
import AuthProvider from './providers/auth-provider';
import AppLayout from './components/AppLayout';

export const metadata = {
  title: 'next-demo',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Theme>
          <AuthProvider>
            <AppLayout>{children}</AppLayout>
          </AuthProvider>
        </Theme>
      </body>
    </html>
  );
}
