import '@radix-ui/themes/styles.css';
import './global.css';
import AuthProvider from './providers/auth-provider';
import HomeProvider from './providers/home-provider';
import AppLayout from './components/AppLayout';
import { RootThemeWrapper } from './components/RootThemeWrapper';

export const metadata = {
  title: 'next-demo',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <RootThemeWrapper>
          <AuthProvider>
            <HomeProvider>
              <AppLayout>{children}</AppLayout>
            </HomeProvider>
          </AuthProvider>
        </RootThemeWrapper>
      </body>
    </html>
  );
}
