# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/ambv/black
    rev: 23.12.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: python -m unittest discover -s ./projects/grind-75
        language: python
        pass_filenames: false
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest projects/vibecheck/
        language: python
        pass_filenames: false
        additional_dependencies:
          [pytest, flask, flask_cors, sqlalchemy, bcrypt, flask_login]
