# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/ambv/black
    rev: 23.12.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: grind-75-tests
        name: Grind 75 unit tests.
        entry: python -m unittest discover -s ./projects/grind-75/grind-75-python
        language: python
        pass_filenames: false
      # - id: vibecheck-flask-tests
      #   name: Vibeheck Flask unit tests.
      #   entry: pytest projects/vibecheck/vibecheck-flask
      #   language: python
      #   pass_filenames: false
      #   additional_dependencies:
      #     [pytest, flask, flask_cors, sqlalchemy, bcrypt, flask_login]
  - repo: local
    hooks:
      - id: flask-demo-tests
        name: Test Flask Demo
        entry: ./projects/demo-apps/flask-demo/venv/bin/pytest projects/demo-apps/flask-demo
        language: python
        types: [python]
        pass_filenames: false
        always_run: true
        additional_dependencies: [flask]
  - repo: local
    hooks:
      - id: toronto-alerts-flask
        name: Toronto Alerts
        entry: ./projects/toronto-alerts/toronto-alerts-flask/venv/bin/pytest projects/toronto-alerts/toronto-alerts-flask
        language: python
        types: [python]
        pass_filenames: false
        always_run: true
        additional_dependencies: [flask]
