owner: iamharryliu
repo: uptime

sites:
  - name: staging-docs
    url: https://staging-docs-md.pages.dev/
  - name: staging-links
    url: https://staging-links-react.pages.dev/
  - name: staging-cloud-8-skate
    url: https://staging-cloud-8-skate-react.pages.dev/
  - name: staging-harryliu-dev
    url: https://staging-harryliu-dev-react.pages.dev/
  - name: staging-harryliu-dev-resume
    url: https://staging-harryliu-dev-react.pages.dev/resume
  - name: staging-findme
    url: https://staging-findme.vercel.app/
  - name: staging-hearth
    url: https://staging-hearth.vercel.app/login
  - name: staging-service-manager
    url: https://staging-vb-express.fly.dev/
  - name: staging-component-library
    url: https://staging-component-library.pages.dev/
  - name: staging-utilities
    url: https://staging-utilities-ui.pages.dev/
  - name: staging-whiteboard
    url: https://staging-whiteboard.vercel.app/
  - name: staging-weather
    url: https://staging-weather-next.vercel.app/
  - name: staging-vb-manager-next-mobile
    url: https://staging-vb-manager-next-mobile.vercel.app/login
  - name: production-cloud-8-skate
    url: https://cloud8skate.com/
  - name: production-harryliu-dev
    url: https://harryliu.dev/
  - name: production-harryliu-dev-resume
    url: https://harryliu.dev/resume
  - name: production-git
    url: https://git.harryliu.dev/
  - name: production-code-server
    url: https://code.harryliu.dev/login
  - name: production-drive
    url: https://drive.harryliu.dev/
  - name: production-nx-cache
    url: https://nx-cache.harryliu.dev/health
  - name: production-observability-vm
    url: https://loki.harryliu.dev/health
  - name: production-socket-server
    url: https://socket.harryliu.dev/health
  - name: production-findme
    url: https://findme.harryliu.dev/
  - name: production-hearth
    url: https://production-hearth.vercel.app/login
  - name: production-service-manager
    url: https://api.harryliu.dev/
  - name: production-component-library
    url: https://components.harryliu.dev/
  - name: production-utilities
    url: https://utilities.harryliu.dev/
  - name: production-whiteboard
    url: https://whiteboard.harryliu.dev/
  - name: production-weather
    url: https://weather.harryliu.dev/
  - name: production-vb-manager-next-mobile
    url: https://production-vb-manager-next-mobile.vercel.app/login
  - name: production-docs
    url: https://docs.harryliu.dev/
  - name: production-links
    url: https://links.harryliu.dev/
  - name: demo-employee-handler-ui
    url: https://demo-employee-handler-ui.vercel.app/

user-agent: upptime-vigilant-broccoli
status-website:
  cname: upptime.harryliu.dev
  name: Harry Liu Status

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

assignees:
  - iamharryliu
