owner: iamharryliu
repo: vigilant-broccoli

sites:
  - name: harryliu.dev
    url: https://harryliu.dev/
  - name: git.harryliu.dev
    url: https://git.harryliu.dev/
  - name: code.harryliu.dev
    url: https://code.harryliu.dev/login
  - name: cloud8skate.com
    url: https://cloud8skate.com/
  - name: findme
    url: https://findme-kohl.vercel.app/
  - name: hearth
    url: https://vb-hearth.vercel.app/login
  - name: whiteboard
    url: https://whiteboard-one-psi.vercel.app/
  - name: service-manager
    url: https://vb-express.fly.dev/
  - name: llm-service
    url: https://vb-llm-service.fly.dev/
    icon: https://vb-llm-service.fly.dev/favicon.ico
  - name: email-service
    url: https://vb-email-service.fly.dev/
  - name: email-subscription-service
    url: https://email-subscription-service.fly.dev/
  - name: storage-service
    url: https://vb-storage-service.fly.dev/
  - name: socker-server
    url: https://socket.harryliu.dev/health

user-agent: upptime-vigilant-broccoli

assignees:
  - iamharryliu
