export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  MY_HOME: '/home',
  HOMES: '/homes',
  WHERE_IS: '/where-is',
  AUTH_CALLBACK: '/auth/callback',
  CALENDAR: '/calendar',
  OVERALL_CALENDAR: '/calendar/overall',
  HOME_CALENDAR: (id: string | number) => `/homes/${id}/calendar`,
  LEISURE: '/leisure',
  RESOURCES: '/resources',
  TASKS: '/tasks',
  HOUSEHOLD_RULES: '/household-rules',
  PRICE_TRACKER: '/price-tracker',
  CHORES: '/chores',
  PROJECTS: '/projects',
  MEALS: '/meals',
  DOCS: '/docs',
  SETTINGS: '/settings',
  USER_SETTINGS: '/user-settings',
} as const;
