export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  HOMES: '/homes',
  WHERE_IS: '/where-is',
  WHERE_IS_DETAIL: (id: string) => `/where-is/${id}`,
  AUTH_CALLBACK: '/auth/callback',
  CALENDAR: '/calendar',
  MASTER_LIST: '/master-list',
  OVERALL_CALENDAR: '/calendar/overall',
  HOME_CALENDAR: (id: string | number) => `/homes/${id}/calendar`,
  LEISURE: '/leisure',
  LEISURE_DETAIL: (id: string) => `/leisure/${id}`,
  RESOURCES: '/resources',
  RESOURCES_DETAIL: (id: string) => `/resources/${id}`,
  HOUSEHOLD_RULES: '/household-rules',
  HOUSEHOLD_RULES_DETAIL: (id: string) => `/household-rules/${id}`,
  PRICE_TRACKER: '/price-tracker',
  PRICE_TRACKER_DETAIL: (id: string) => `/price-tracker/${id}`,
  CHORES: '/chores',
  PROJECTS: '/projects',
  PROJECTS_DETAIL: (id: string) => `/projects/${id}`,
  MEALS: '/meals',
  MEALS_DETAIL: (id: string) => `/meals/${id}`,
  DOCS: '/docs',
  DOCS_DETAIL: (id: string) => `/docs/${id}`,
  SETTINGS: '/settings',
  USER_SETTINGS: '/user-settings',
} as const;
