name = "cloud-8-skate-angular"
main = "../../dist/apps/ui/cloud-8-skate-angular/server/server.mjs"
compatibility_date = "2024-01-29"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "../../dist/apps/ui/cloud-8-skate-angular/browser"
