packages:
  - 'apps/*'
  - 'apps/api/*'
  - 'apps/cms/*'
  - 'libs/**'
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  better-sqlite3: true
  core-js-pure: true
  esbuild: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  sharp: true
  unrs-resolver: true
  workerd: true
  '@scarf/scarf': false
overrides:
  fastify: $fastify
  fastify-plugin: $fastify-plugin
  '@fastify/cors': $@fastify/cors
  '@slack/bolt': $@slack/bolt
  '@slack/types': $@slack/types
  '@slack/web-api': $@slack/web-api
  next-auth>nodemailer: $nodemailer
  '@slack/bolt>@types/express': $@types/express
