packages:
  - 'apps/*'
  - 'apps/api/*'
  - 'apps/cms/*'
  - 'libs/**'
  - 'packages/*'
overrides:
  '@slack/web-api': ^7.17.0
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  better-sqlite3: true
  core-js-pure: true
  esbuild: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  sharp: true
  unrs-resolver: true
  workerd: true
  husky: true
  '@scarf/scarf': false
