app = 'vb-express'
primary_region = 'yyz'

[build]

[env]
  PORT = '3000'
  HOST = '0.0.0.0'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpus = 1
  memory_mb = 512
