tap "cormacrelf/tap"
tap "hashicorp/tap"
tap "teamookla/speedtest"
# Codec library for encoding and decoding AV1 video streams
brew "aom"
# Official Amazon AWS command-line interface
brew "awscli"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Core application library for C
brew "glib"
# Vector graphics library with cross-device output support
brew "cairo"
# Fix common misspellings in source code and text files
brew "codespell"
# Tool for managing dock items
brew "dockutil"
# Perl lib for reading and writing EXIF metadata
brew "exiftool"
# Play, record, convert, and stream select audio and video codecs
brew "ffmpeg"
# Command-line tools for fly.io services
brew "flyctl"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Audit git repos for secrets
brew "gitleaks"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# OpenType text shaping engine
brew "harfbuzz"
# Network logon cracker which supports many services
brew "hydra"
# TIFF library and utilities
brew "libtiff"
# Tools and libraries to manipulate images in select formats
brew "imagemagick"
# CLI wrapper for basic network utilities on macOS - ip command
brew "iproute2mac"
# Featureful UNIX password cracker
brew "john"
# Simple terminal UI for git commands
brew "lazygit"
# Subtitle renderer for the ASS/SSA subtitle format
brew "libass"
# C library of Git core methods that is re-entrant and linkable
brew "libgit2"
# Simple tool to make locally trusted development certificates
brew "mkcert"
# Open source relational database management system
brew "mysql"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# No Nonsense Neovim Client in Rust
brew "neovide"
# Port scanning utility for large networks
brew "nmap"
# Open-source, cross-platform JavaScript runtime environment
brew "node@22", link: true
# Libraries for security-enabled client and server applications
brew "nss"
# Manage multiple Node.js versions
brew "nvm"
# Pinentry for GPG on Mac
brew "pinentry-mac"
# Execute binaries from Python packages in isolated environments
brew "pipx"
# Fast, disk space efficient package manager
brew "pnpm"
# Cross-platform library for audio I/O
brew "portaudio"
# Object-relational database system
brew "postgresql@15"
# Theme for zsh
brew "powerlevel10k"
# Framework for managing multi-language pre-commit hooks
brew "pre-commit"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Interpreted, interactive, object-oriented programming language
brew "python@3.11"
# Interpreted, interactive, object-oriented programming language
brew "python@3.12"
# Command-line interface for https://speedtest.net bandwidth tests
brew "speedtest-cli"
# OCR (Optical Character Recognition) engine
brew "tesseract"
# Linter for Terraform files
brew "tflint"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Internet file retriever
brew "wget"
# Tools for the WireGuard secure network tunnel
brew "wireguard-tools"
# Blazing fast terminal file manager written in Rust, based on async I/O
brew "yazi"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Enable Windows-like alt-tab
cask "alt-tab"
# Application uninstaller
cask "appcleaner"
# Tool to flash OS images to SD cards & USB drives
cask "balenaetcher"
# Swedish personal electronic identification (eID) system
cask "bankid"
# Desktop password and login vault
cask "bitwarden"
# Open source IDE for exploring and testing APIs
cask "bruno"
# Terminal-based AI coding assistant
cask "claude-code@latest"
# Browser for SQLite databases
cask "db-browser-for-sqlite"
# Universal database tool and SQL client
cask "dbeaver-community"
# App to build and share containerised applications and microservices
cask "docker-desktop"
# Productivity app
cask "dropzone"
# Web browser
cask "firefox"
cask "font-symbols-only-nerd-font"
# Set of tools to manage resources and applications hosted on Google Cloud
cask "gcloud-cli"
# Desktop client for GitHub repositories
cask "github"
# 2D and 3D game engine
cask "godot"
# Web browser
cask "google-chrome"
# Client for the Google Drive storage service
cask "google-drive"
# Speech to text application
cask "handy"
# Tool to optimise images to a smaller size
cask "imageoptim"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Host-based application firewall
cask "little-snitch"
# VPN client for secure internet access and private browsing
cask "nordvpn"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Retro video game emulation
cask "openemu"
# Control your tools with a few keystrokes
cask "raycast"
# Free Dj app to prepare and manage your music files
cask "rekordbox"
# File sync and share software
cask "resilio-sync"
# Plugin for AWS CLI to start and end sessions that connect to managed instances
cask "session-manager-plugin"
# Music streaming service
cask "spotify"
# Video game digital distribution service
cask "steam"
# Mesh VPN based on WireGuard
cask "tailscale-app"
# Open-source code editor
cask "visual-studio-code"
# Create, manage, and run virtual machines
cask "vmware-fusion"
# Free messaging and calling application
cask "wechat"
# Native desktop client for WhatsApp
cask "whatsapp"
# Network protocol analyzer
cask "wireshark-app"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "github.github-vscode-theme"
vscode "golang.go"
vscode "gruntfuggly.todo-tree"
vscode "johnpapa.vscode-peacock"
vscode "mechatroner.rainbow-csv"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "nrwl.angular-console"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "usernamehw.errorlens"
vscode "xabikos.javascriptsnippets"
go "golang.org/x/tools/gopls"
go "honnef.co/go/tools/cmd/staticcheck"
