export const ENVIRONMENT = {
  PRODUCTION: false,
  RECAPTCHA_V3_SITE_KEY: '6LfAdbMoAAAAAOR8IRGqw-3gPj8Fdl5GHqm6wzOF',
  ANALYTICS_ID: 'G-SJELMQXML9',
  URLS: {
    PERSONAL_WEBSITE_BACKEND_URL: 'http://localhost:3000',
  },
};
