import { createSwaggerSpec } from '@vigilant-broccoli/fastify';

const SERVICE_TITLE = 'vb-manager-local-fastify';
const SERVICE_DESCRIPTION =
  'Local-only API behind VB Manager. Every /api route except /api/auth/* requires an Authorization: Bearer <Supabase access token> header.';
const PATH_PARAM_PATTERN = /\{(\w+)\}/g;

type HttpMethod = 'get' | 'post' | 'put' | 'patch' | 'delete';

const API_ROUTES: Record<string, HttpMethod[]> = {
  '/api/api-keys': ['get', 'post'],
  '/api/api-keys/{id}': ['patch', 'delete'],
  '/api/auth/google-token': ['post'],
  '/api/aws/profiles': ['get'],
  '/api/bucket': ['get', 'post', 'delete'],
  '/api/calendar/events': ['get', 'post'],
  '/api/calendar/parse': ['post'],
  '/api/chat': ['post'],
  '/api/chat/publish': ['post'],
  '/api/disk-space': ['get'],
  '/api/dj/download': ['post'],
  '/api/dj/open-rekordbox': ['post'],
  '/api/dj/playlists': ['get'],
  '/api/docker/containers': ['get'],
  '/api/docker/remove': ['post'],
  '/api/docker/start': ['post'],
  '/api/docker/stop': ['post'],
  '/api/event-calendars': ['get', 'post'],
  '/api/event-calendars/{id}': ['patch', 'delete'],
  '/api/event-calendars/{id}/sync': ['get', 'post'],
  '/api/event-calendars/untracked': ['get'],
  '/api/event-calendars/untracked/{calendarId}': ['delete'],
  '/api/flyio/apps': ['get'],
  '/api/flyio/auth/login': ['post'],
  '/api/gcloud/auth-status': ['get'],
  '/api/gcloud/projects': ['get'],
  '/api/gcloud/reauth-needed': ['get'],
  '/api/gcloud/set-account': ['post'],
  '/api/gcloud/set-project': ['post'],
  '/api/gcloud/vault-token': ['post'],
  '/api/generate-secret': ['get'],
  '/api/github/organization-members': ['post', 'delete'],
  '/api/github/organization-structure': ['get'],
  '/api/github/organization/members': ['get'],
  '/api/github/organization/meta': ['get'],
  '/api/github/organization/repositories': ['get', 'post', 'delete'],
  '/api/github/organization/teams': ['get', 'post', 'delete'],
  '/api/github/pages': ['get'],
  '/api/github/user/organizations': ['get'],
  '/api/kanban/boards': ['get', 'put'],
  '/api/language-learning/define': ['post'],
  '/api/language-learning/history': ['get'],
  '/api/language-learning/mastered': ['get', 'post', 'delete'],
  '/api/language-learning/reset': ['delete'],
  '/api/language-learning/words': ['post'],
  '/api/llm-test': ['post'],
  '/api/local-ip': ['get'],
  '/api/local-machine': ['get'],
  '/api/local-services': ['get'],
  '/api/network-monitor/lan-devices': ['get'],
  '/api/network-monitor/outbound-connections': ['get'],
  '/api/network-monitor/scan-device': ['post'],
  '/api/notepad': ['get', 'post'],
  '/api/outfit-recommendation': ['get'],
  '/api/pm2/delete': ['post'],
  '/api/pm2/processes': ['get'],
  '/api/pm2/restart': ['post'],
  '/api/pm2/start': ['post'],
  '/api/pm2/stop': ['post'],
  '/api/public-ip': ['get'],
  '/api/qr-code': ['post'],
  '/api/recipe/scrape': ['post'],
  '/api/recipe/scrape-preview': ['post'],
  '/api/resume': ['get', 'put'],
  '/api/resume/chat': ['post'],
  '/api/resume/pdf': ['post'],
  '/api/send-email-message': ['post'],
  '/api/send-text-message': ['post'],
  '/api/shell/execute': ['post'],
  '/api/speech-to-text': ['post'],
  '/api/speed-test': ['get'],
  '/api/ssh-key': ['get'],
  '/api/stripe/checkout-session': ['post'],
  '/api/tailscale/machines': ['get'],
  '/api/tasks': ['get', 'post', 'patch', 'delete'],
  '/api/tasks/create': ['post'],
  '/api/tasks/lists': ['get', 'post', 'patch', 'delete'],
  '/api/tasks/move': ['post'],
  '/api/tasks/parse-image': ['post'],
  '/api/tasks/parse-text': ['post'],
  '/api/terraform/status': ['get'],
  '/api/text-to-speech': ['post'],
  '/api/todo': ['get', 'put'],
  '/api/todo/solve': ['post'],
  '/api/vercel/projects': ['get'],
  '/api/voice-list': ['post'],
  '/api/weather': ['get'],
  '/api/wireguard/status': ['get'],
  '/api/wrangler/login': ['post'],
  '/api/wrangler/pages': ['get', 'delete'],
};

const toOperation = (path: string) => ({
  parameters: [...path.matchAll(PATH_PARAM_PATTERN)].map(([, name]) => ({
    name,
    in: 'path',
    required: true,
    schema: { type: 'string' },
  })),
  responses: {
    '200': { description: 'OK' },
    '401': { description: 'Unauthorized' },
  },
});

export const swaggerSpec = createSwaggerSpec({
  title: SERVICE_TITLE,
  description: SERVICE_DESCRIPTION,
  paths: Object.fromEntries(
    Object.entries(API_ROUTES).map(([path, methods]) => [
      path,
      Object.fromEntries(methods.map(method => [method, toOperation(path)])),
    ]),
  ),
});
