export const APP_ACTION = {
  WORKDAY_CHECKBOXES: 'WORKDAY_CHECKBOXES',
  OPEN_SCHEDULE_MODAL: 'OPEN_SCHEDULE_MODAL',
  SUBMIT_SCHEDULE: 'SUBMIT_SCHEDULE',
  OPEN_SETTINGS_MODAL: 'OPEN_SETTINGS_MODAL',
  OPEN_ASK_LUNCH_MODAL: 'OPEN_ASK_LUNCH_MODAL',
  SUBMIT_SETTINGS: 'SUBMIT_SETTINGS',
  ASK_LUNCH: 'ASK_LUNCH',
  SUBMIT_CHECKOUT: 'SUBMIT_CHECKOUT',
};
