#!/bin/bash

echo "📦 REPOSITORY"
echo "  open:repo                   Open GitHub repo"
echo "  open:repo:actions           Open GitHub Actions"
echo "  npm:packages                Open npm packages page"
echo ""
echo "⚙️  SETUP"
echo "  local:install:machine-setup Run machine setup installer (mac/linux)"
echo "  format                      Format all files with Prettier"
echo "  cloud:login                 Login to GCP and GitHub CLI"
echo "  gcp:login                   Login to GCP and set project"
echo "  gh:login                    Login to GitHub CLI"
echo "  npm:login                   Login to npm"
echo "  oracle:config               Edit OCI config"
echo ""
echo "🏗️  TERRAFORM"
echo "  tf:plan                     Load vault env and run terraform plan"
echo "  tf:import                   Load vault env and run terraform import <address> <id>"
echo "  tf:apply                    Load vault env, apply terraform, and run post-apply"
echo "  tf:post-apply               Run post-apply script"
echo "  tf:output                   Show terraform outputs"
echo ""
echo "☁️  OCI"
echo "  oci:vm:ssh                  SSH into OCI VM (RabbitMQ)"
echo "  oci:vm:sync-socket-token    Sync socket-server SENDER_TOKEN with Vault (run after rotation)"
echo "  oci:gitea:ssh               SSH into Gitea VM"
echo ""
echo "💻 CODE SERVER"
echo "  oci:code-server:open        Open code.harryliu.dev"
echo "  oci:code-server:password    Copy code-server password to clipboard"
echo "  oci:code-server:ssh         SSH into code-server VM"
echo "  oci:code-server:logs        Follow code-server container logs"
echo "  oci:code-server:logs:cloud-init  Follow VM provisioning log"
echo "  oci:code-server:reset       Rebuild containers + volumes (fresh environment)"
echo "  oci:code-server:replace     Replace the VM via terraform (fresh host)"
echo ""
echo "🖥️  GCP VM"
echo "  gcp:vm:image:build          Build GCP VM Packer image (init + build)"
echo "  gcp:vm:ssh                  SSH into GCP VM via IAP"
echo "  gcp:vm:status               Get GCP VM status"
echo "  gcp:vm:stop                 Stop GCP VM"
echo "  gcp:vm:start                Start GCP VM"
echo "  gcp:vm:post-init            Run Vault post-init script"
echo "  gcp:vm:regen-cert           Regenerate cert and update WireGuard"
echo "  gcp:vm:update-wg            Update WireGuard endpoint"
echo ""
echo "🔐 VAULT"
echo "  gcp:vm:vault:test-local-connection  Test local Vault connection"
echo "  gcp:vm:vault:unseal         Unseal Vault"
echo "  gcp:vm:vault:seal           Seal Vault"
echo "  gcp:vm:vault:save-secrets-local     Save Vault secrets locally"
echo "  gcp:vm:vault:set-secrets    Set secrets in Vault"
echo ""
echo "🔑 SECRETS"
echo "  secret-rotation:all         Run all scripted rotations, then dispatch rotate-secrets workflow"
echo "  secret-rotation:flyio       Rotate Fly.io token"
echo "  secret-rotation:gitea       Rotate Gitea CI token (scoped read:repository)"
echo "  secret-rotation:profile-deploy-key  Rotate profile repo deploy key, store in Vault"
echo "  secret-rotation:resend      Rotate Resend API key (single-key swap, pushes to fly app)"
echo ""
echo "🐳 LOCAL"
echo "  local:docker:up             Start local Docker Compose services"
echo "  local:docker:down           Stop local Docker Compose services"
echo "  local:docker:restart        Restart local Docker Compose services"
echo "  local:docker:reload         Reload local Docker Compose services"
echo "  health-check                Run health check script"
echo ""
echo "🏠 HOMELAB"
echo "  homelab:up                  Start homelab services and Tailscale"
echo "  homelab:down                Stop homelab services and Tailscale"
echo "  homelab:restart             Restart homelab services"
echo "  homelab:logs                Tail homelab service logs"
echo "  homelab:ps                  List homelab service status"
echo "  homelab:pull                Pull latest homelab images"
echo ""
echo "🐙 GITHUB"
echo "  gh:board:sync               Sync GitHub project board"
echo "  gh:actions:deploy           Trigger deploy workflow"
echo "  gh:actions:health-check     Trigger health-check workflow"
echo "  gh:actions:kill-services    Trigger kill-services workflow"
echo "  gh:actions:rotate-secrets   Trigger rotate-secrets workflow (prompts for confirm)"
echo "  gh:actions:run-tests        Trigger all post-deploy test workflows"
echo "  gh:actions:replace-code-server  Trigger code-server VM replace workflow"
echo ""
echo "🔍 AUDIT"
echo "  audit                       Run vulnerability audit tree"
