#!/bin/bash

echo "📦 REPOSITORY"
echo "  open:repo                   Open GitHub repo"
echo "  open:repo:actions           Open GitHub Actions"
echo "  npm:packages                Open npm packages page"
echo ""
echo "⚙️  SETUP"
echo "  install-all                 Recursively install all npm dependencies"
echo "  format                      Format all files with Prettier"
echo "  npm:login                   Login to npm"
echo "  gh:login                    Login to GitHub CLI"
echo "  gcp:login                   Login to GCP and set project"
echo "  oracle:config               Edit OCI config"
echo ""
echo "🏗️  TERRAFORM"
echo "  tf:plan                     Load vault env and run terraform plan"
echo "  tf:apply                    Load vault env, apply terraform, and run post-apply"
echo "  tf:post-apply               Run post-apply script"
echo "  tf:output                   Show terraform outputs"
echo ""
echo "☁️  OCI"
echo "  oci:vm:ssh                  SSH into OCI VM (RabbitMQ)"
echo ""
echo "🖥️  GCP VM"
echo "  gcp:vm:image:build          Build GCP VM Packer image (init + build)"
echo "  gcp:vm:ssh                  SSH into GCP VM via IAP"
echo "  gcp:vm:status               Get GCP VM status"
echo "  gcp:vm:stop                 Stop GCP VM"
echo "  gcp:vm:start                Start GCP VM"
echo "  gcp:vm:post-init            Run Vault post-init script"
echo "  gcp:vm:regen-cert           Regenerate cert and update WireGuard"
echo "  gcp:vm:update-wg            Update WireGuard endpoint"
echo ""
echo "🔐 VAULT"
echo "  gcp:vm:vault:test-local-connection  Test local Vault connection"
echo "  gcp:vm:vault:unseal         Unseal Vault"
echo "  gcp:vm:vault:seal           Seal Vault"
echo "  gcp:vm:vault:save-secrets-local     Save Vault secrets locally"
echo "  gcp:vm:vault:set-secrets    Set secrets in Vault"
echo ""
echo "🔑 SECRETS"
echo "  secret-rotation:flyio       Rotate Fly.io token"
echo ""
echo "🐳 LOCAL"
echo "  local:docker:up             Start local Docker Compose services"
echo "  local:docker:down           Stop local Docker Compose services"
echo "  local:docker:restart        Restart local Docker Compose services"
echo "  local:docker:reload         Reload local Docker Compose services"
echo "  health-check                Run health check script"
echo ""
echo "🏠 HOMELAB"
echo "  homelab:up                  Start homelab services and Tailscale"
echo "  homelab:down                Stop homelab services and Tailscale"
echo "  homelab:restart             Restart homelab services"
echo "  homelab:logs                Tail homelab service logs"
echo "  homelab:ps                  List homelab service status"
echo "  homelab:pull                Pull latest homelab images"
echo ""
echo "🐙 GITHUB"
echo "  gh:board:sync               Sync GitHub project board"
echo "  gh:actions:deploy           Trigger deploy workflow"
echo "  gh:actions:health-check     Trigger health-check workflow"
echo "  gh:actions:kill-services    Trigger kill-services workflow"
echo "  gh:actions:test-services    Trigger all service test workflows"
echo ""
echo "🔍 AUDIT"
echo "  audit                       Run vulnerability audit tree"
