name: Deploy FlyIO - Deploy App
on:
  push: { branches: ['main'] }

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLYIO_AUTH_TOKEN }}
    environment:
      name: production
    defaults:
      run:
        working-directory: [dir]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --dockerfile [dockerfile] --config [toml_config_file]
