from unittest.mock import patch, Mock
from App.const import HTTP_STATUS_CODE

weather_mock_data = {
    "coord": {"lon": 10.99, "lat": 44.34},
    "weather": [
        {
            "id": 501,
            "main": "Rain",
            "description": "moderate rain",
            "icon": "10d",
        }
    ],
    "base": "stations",
    "main": {
        "temp": 298.48,
        "feels_like": 298.74,
        "temp_min": 297.56,
        "temp_max": 300.05,
        "pressure": 1015,
        "humidity": 64,
        "sea_level": 1015,
        "grnd_level": 933,
    },
    "visibility": 10000,
    "wind": {"speed": 0.62, "deg": 349, "gust": 1.18},
    "rain": {"1h": 3.16},
    "clouds": {"all": 100},
    "dt": 1661870592,
    "sys": {
        "type": 2,
        "id": 2075663,
        "country": "IT",
        "sunrise": 1661834187,
        "sunset": 1661882248,
    },
    "timezone": 7200,
    "id": 3163858,
    "name": "Zocca",
    "cod": 200,
}

ttc_mock_data = {
    "total": 7,
    "lastUpdated": "2024-07-11T09:40:35.503Z",
    "routes": [
        {
            "id": "35028",
            "priority": 1,
            "alertType": "Planned",
            "lastUpdated": "2024-07-10T15:27:12.06Z",
            "activePeriod": {
                "start": "2024-07-10T15:27:12.06Z",
                "end": "2024-07-13T06:00:00Z",
            },
            "activePeriodGroup": ["Current", "Weekend"],
            "routeOrder": 2,
            "route": "2",
            "routeBranch": "",
            "routeTypeSrc": "400",
            "routeType": "Subway",
            "stopStart": "Kipling",
            "stopEnd": "Keele",
            "title": "This weekend, there will be no subway service on Line 2 Bloor-Danforth between Kipling and Keele due to planned track work. Shuttle buses will operate between Kipling and Keele.",
            "description": "",
            "url": "",
            "urlPlaceholder": "",
            "accessibility": "Routes",
            "effect": "NO_SERVICE",
            "effectDesc": "Subway Closure - This Weekend",
            "severityOrder": 3,
            "severity": "Major",
            "customHeaderText": "This weekend, there will be no subway service on Line 2 Bloor-Danforth between Kipling and Keele due to planned track work. Shuttle buses will operate between Kipling and Keele.",
            "headerText": "This weekend, there will be no subway service on Line 2 Bloor-Danforth between Kipling and Keele due to planned track work. Shuttle buses will operate between Kipling and Keele.",
        },
        {
            "id": "35050",
            "priority": 0,
            "alertType": "Planned",
            "lastUpdated": "2024-07-11T09:39:44.377Z",
            "activePeriod": {
                "start": "2024-07-11T09:39:44.377Z",
                "end": "2024-07-11T09:54:44.377Z",
            },
            "activePeriodGroup": ["Current"],
            "routeOrder": 36,
            "route": "36",
            "routeBranch": "",
            "routeTypeSrc": "700",
            "routeType": "Bus",
            "stopStart": "Finch Ave West at Oakdale Rd - Humber Reactivation Care",
            "stopEnd": "Finch Ave West at Oakdale Rd - Humber Reactivation Care",
            "title": "36 Finch West Regular service has resumed eastbound near Finch Ave West at Oakdale Rd - Humber Reactivation Care.",
            "description": "",
            "url": "",
            "urlPlaceholder": "",
            "accessibility": "Routes",
            "effect": "OTHER_EFFECT",
            "effectDesc": "Regular service",
            "severityOrder": 6,
            "severity": "Minor",
            "customHeaderText": None,
            "headerText": "36 Finch West Regular service has resumed eastbound near Finch Ave West at Oakdale Rd - Humber Reactivation Care.",
        },
        {
            "id": "35053",
            "priority": 0,
            "alertType": "Planned",
            "lastUpdated": "2024-07-11T09:40:35.503Z",
            "activePeriod": {
                "start": "2024-07-11T09:40:35.503Z",
                "end": "2024-07-11T09:55:35.503Z",
            },
            "activePeriodGroup": ["Current"],
            "routeOrder": 84,
            "route": "84D",
            "routeBranch": "D",
            "routeTypeSrc": "700",
            "routeType": "Bus",
            "stopStart": "Oakdale Rd at Finch Ave West South Side - Humber Reactivation Care",
            "stopEnd": "Oakdale Rd at Finch Ave West South Side - Humber Reactivation Care",
            "title": "84D Sheppard West Regular service has resumed near Oakdale Rd at Finch Ave West South Side - Humber Reactivation Care.",
            "description": "",
            "url": "",
            "urlPlaceholder": "",
            "accessibility": "Routes",
            "effect": "OTHER_EFFECT",
            "effectDesc": "Regular service",
            "severityOrder": 6,
            "severity": "Minor",
            "customHeaderText": None,
            "headerText": "84D Sheppard West Regular service has resumed near Oakdale Rd at Finch Ave West South Side - Humber Reactivation Care.",
        },
    ],
    "accessibility": [
        {
            "id": "35014",
            "priority": 0,
            "alertType": "Planned",
            "lastUpdated": "2024-07-10T08:02:11.933Z",
            "activePeriod": {
                "start": "2024-07-10T08:02:11.933Z",
                "end": "0001-01-01T00:00:00Z",
            },
            "activePeriodGroup": ["Current"],
            "routeOrder": 0,
            "route": "2,26,35,55,300",
            "routeBranch": ",,,,",
            "routeTypeSrc": "1303",
            "routeType": "Elevator",
            "stopStart": None,
            "stopEnd": None,
            "title": "Elevator Out of service between concourse and Line 2 Kennedy platform.",
            "description": "",
            "url": "https://www.ttc.ca/subway-stations/jane-station",
            "urlPlaceholder": "Accessible alternatives:",
            "accessibility": "Elevator",
            "effect": "NO_SERVICE",
            "effectDesc": "Out of service",
            "severityOrder": 1,
            "severity": "Critical",
            "customHeaderText": "",
            "headerText": "Jane: Elevator Out of service between concourse and Line 2 Kennedy platform.",
        },
        {
            "id": "34910",
            "priority": 0,
            "alertType": "Planned",
            "lastUpdated": "2024-07-07T03:55:31.543Z",
            "activePeriod": {
                "start": "2024-07-07T03:55:31.543Z",
                "end": "0001-01-01T00:00:00Z",
            },
            "activePeriodGroup": ["Current"],
            "routeOrder": 0,
            "route": "2,13,19,97,300",
            "routeBranch": ",,,,",
            "routeTypeSrc": "1303",
            "routeType": "Elevator",
            "stopStart": None,
            "stopEnd": None,
            "title": "Elevator Out of service between Cumberland Terrace entrance and concourse.",
            "description": "",
            "url": "https://www.ttc.ca/subway-stations/bay-station",
            "urlPlaceholder": "Accessible alternatives:",
            "accessibility": "Elevator",
            "effect": "NO_SERVICE",
            "effectDesc": "Out of service",
            "severityOrder": 1,
            "severity": "Critical",
            "customHeaderText": "",
            "headerText": "Bay: Elevator Out of service between Cumberland Terrace entrance and concourse.",
        },
        {
            "id": "34615",
            "priority": 0,
            "alertType": "Planned",
            "lastUpdated": "2024-06-28T14:24:04.913Z",
            "activePeriod": {
                "start": "2024-06-28T14:24:04.913Z",
                "end": "0001-01-01T00:00:00Z",
            },
            "activePeriodGroup": ["Current"],
            "routeOrder": 0,
            "route": "1,19,97,320",
            "routeBranch": ",,,",
            "routeTypeSrc": "1303",
            "routeType": "Elevator",
            "stopStart": None,
            "stopEnd": None,
            "title": "Elevator Out of service between 10 Dundas St E entrance and Line 1 Finch platform.",
            "description": "",
            "url": "https://www.ttc.ca/subway-stations/dundas-station",
            "urlPlaceholder": "Accessible alternatives:",
            "accessibility": "Elevator",
            "effect": "NO_SERVICE",
            "effectDesc": "Out of service",
            "severityOrder": 1,
            "severity": "Critical",
            "customHeaderText": "",
            "headerText": "Dundas: Elevator Out of service between 10 Dundas St E entrance and Line 1 Finch platform.",
        },
    ],
    "siteWide": None,
    "siteWideCustom": [
        {
            "id": "35028",
            "priority": 1,
            "alertType": "Planned",
            "lastUpdated": "2024-07-10T15:27:12.06Z",
            "activePeriod": {
                "start": "2024-07-10T15:27:12.06Z",
                "end": "2024-07-13T06:00:00Z",
            },
            "activePeriodGroup": ["Current", "Weekend"],
            "routeOrder": 2,
            "route": "2",
            "routeBranch": "",
            "routeTypeSrc": "400",
            "routeType": "Subway",
            "stopStart": "Kipling",
            "stopEnd": "Keele",
            "title": "This weekend, there will be no subway service on Line 2 Bloor-Danforth between Kipling and Keele due to planned track work. Shuttle buses will operate between Kipling and Keele.",
            "description": "",
            "url": "",
            "urlPlaceholder": "",
            "accessibility": "Routes",
            "effect": "NO_SERVICE",
            "effectDesc": "Subway Closure - This Weekend",
            "severityOrder": 3,
            "severity": "Major",
            "customHeaderText": "This weekend, there will be no subway service on Line 2 Bloor-Danforth between Kipling and Keele due to planned track work. Shuttle buses will operate between Kipling and Keele.",
            "headerText": "This weekend, there will be no subway service on Line 2 Bloor-Danforth between Kipling and Keele due to planned track work. Shuttle buses will operate between Kipling and Keele.",
        }
    ],
    "generalCustom": [],
    "status": "success",
}
alerts_response = ""


def test_index(client):
    with patch("requests.get") as mock_get:
        mock_response1 = Mock()
        mock_response1.json.return_value = weather_mock_data
        mock_response2 = Mock()
        mock_response2.json.return_value = ttc_mock_data
        mock_response3 = Mock()
        mock_response3.status_code = 200
        mock_response3.content = "".encode("utf-8")
        mock_get.side_effect = [
            mock_response1,
            mock_response2,
            # TODO: fix double call
            mock_response3,
            mock_response3,
        ]
        response = client.get("/")
        assert response.status_code == HTTP_STATUS_CODE.OKAY
