app = "app-monitor-api"
primary_region = "yyz"

[build]

[env]
  HOST = "0.0.0.0"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = ""
  internal_port = 3000

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
