class APP_CONFIG:
    SECRET_KEY = "secret key"


class USER_CONFIG:
    MAX_USERNAME_LENGTH = 30
    MAX_EMAIL_LENGTH = 30
    MAX_PASSWORD_LENGTH = 30


class HTTP_STATUS_CODES:
    OKAY = 200
    BAD_REQUEST = 400
    UNAUTHORIZED_REQUEST = 401
    FORBIDDEN_REQUEST = 403
    NOT_FOUND_ERROR = 404
    INTERNAL_SERVER_ERROR = 500


class EXCEPTION_CODES:
    BAD_REQUEST = "BAD_REQUEST"
    FORBIDDEN_REQUEST = "FORBIDDEN_REQUEST"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    EXISTING_RESOURCE = "EXISTING_RESOURCE"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
