networks:
  monitoring:
    driver: bridge

services:
  proxy:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    restart: unless-stopped
    networks:
      - monitoring
      - default

  resilio:
    image: linuxserver/resilio-sync:latest
    container_name: resilio-sync
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./resilio/config:/config
      - ~/resilio-sync:/sync
    ports:
      - "28888:8888"
      - "55556:55555"
    restart: unless-stopped
    networks:
      - monitoring
      - default

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - ~/resilio-sync/shared/immich:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - UPLOAD_LOCATION=/data
      - DB_HOSTNAME=database
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=redis
    depends_on:
      - redis
      - database
    restart: unless-stopped
    networks:
      - monitoring
      - default

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    command: ['start.sh', 'microservices']
    volumes:
      - ~/resilio-sync/shared/immich:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - UPLOAD_LOCATION=/data
      - DB_HOSTNAME=database
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=redis
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ./immich/model-cache:/cache
    environment:
      - UPLOAD_LOCATION=/data
      - DB_HOSTNAME=database
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=redis
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: ghcr.io/tensorchord/pgvecto-rs:pg16-v0.2.0
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ./immich/pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: database
    depends_on:
      - database

  loki:
    container_name: loki
    image: grafana/loki:latest
    restart: unless-stopped
    volumes:
      - ./loki/loki.yml:/etc/loki/loki.yml:ro
      - ./loki/data:/loki
    ports:
      - "23100:3100"
    command: -config.file=/etc/loki/loki.yml
    networks:
      - monitoring
      - default

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    restart: unless-stopped
    volumes:
      - ./promtail/promtail.yml:/etc/promtail/promtail.yml:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/promtail.yml
    depends_on:
      - loki
    networks:
      - monitoring
      - default
    user: root

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=https://grafana.vigilant-broccoli.app
    ports:
      - "23000:3000"
    depends_on:
      - loki
    networks:
      - monitoring
      - default
