networks:
  monitoring:
    driver: bridge

services:
  proxy:
    image: nginx:latest
    ports:
      - "127.0.0.1:443:443"
      - "127.0.0.1:80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    restart: unless-stopped
    networks:
      - monitoring
      - default

  loki:
    container_name: loki
    image: grafana/loki:latest
    restart: unless-stopped
    volumes:
      - ./loki/loki.yml:/etc/loki/loki.yml:ro
      - ./loki/data:/loki
    ports:
      - "127.0.0.1:23100:3100"
    command: -config.file=/etc/loki/loki.yml
    networks:
      - monitoring
      - default

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    restart: unless-stopped
    volumes:
      - ./promtail/promtail.yml:/etc/promtail/promtail.yml:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOME}/.pm2/logs/vb-manager-next-error.log:/pm2-logs/vb-manager-next-error.log:ro
      - ${HOME}/.pm2/logs/vb-manager-next-out.log:/pm2-logs/vb-manager-next-out.log:ro
    command: -config.file=/etc/promtail/promtail.yml
    depends_on:
      - loki
    networks:
      - monitoring
      - default
    user: root

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=https://grafana.vigilant-broccoli.app
    ports:
      - "127.0.0.1:23000:3000"
    depends_on:
      - loki
    networks:
      - monitoring
      - default
