class ENDPOINT:
    INDEX = "/"
    SUBSCRIBE = "/subscribe"
    UNSUBSCRUBE = "/unsubscribe"
    VERIFY_EMAIL = "/verify"
    BLOGS = "/blogs"
    BLOG = "/blog"
    GET_USERS = "/get_users"
    TTC = "/ttc"
    WEATHER = "/weather"
    DASHBOARD = "/dashboard"
