import { OPEN_TYPE } from '@vigilant-broccoli/common-js';
import {
  ANTHROPIC_LINK,
  CLAUDE_LINK,
  CLOUDFLARE_LINK,
  DEEPSEEK_LINK,
  FLYIO_LINK,
  GCP_LINK,
  GEMINI_LINK,
  GITHUB_LINK,
  GOOGLE_SERVICES,
  GROK_LINK,
  OPENAI_LINK,
  OPENWEATHER_LINK,
  ROBOFLOW_LINK,
  STRIPE_LINK,
  TERRAFORM_LINK,
  TWILIO_LINK,
  UTILITY_URL,
} from '@vigilant-broccoli/common-js';
import {
  JOURNAL_PATH,
  MAC_OS_APP,
  PERSONAL_URL,
  VB_REPO_PATH,
} from '@vigilant-broccoli/personal-common-js';

const LINK_GROUP_SUBGROUP = {
  UTILITY: 'Utility',
  CAREER: 'Career',
  LEISURE: 'Leisure',
  LEARN: 'Learn',
  FOR_LATER: 'For Later',
  HOME: 'Home',
  DEV: 'Dev',
  VIGILANT_BROCCOLI: 'vigilant-broccoli',
} as const;

const DEV_LINKS = [
  {
    label: GOOGLE_SERVICES.GCP.NAME,
    target: GOOGLE_SERVICES.GCP.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: 'VB - GCP Billing',
    target: 'https://console.cloud.google.com/billing/017A09-73DEB3-7A8E42/reports?inv=1&invt=Ab2jMQ&project=vigilant-broccoli',
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: 'VB - GCE Instances',
    target: 'https://console.cloud.google.com/compute/instances?inv=1&invt=Ab2jIQ&project=vigilant-broccoli',
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: 'Cron Guru',
    target: 'https://crontab.guru/',
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: GITHUB_LINK.GITHUB.NAME,
    target: GITHUB_LINK.GITHUB.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: GITHUB_LINK.TOKENS.NAME,
    target: GITHUB_LINK.TOKENS.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: GITHUB_LINK.ACTIONS_PRICING.NAME,
    target: GITHUB_LINK.ACTIONS_PRICING.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: GITHUB_LINK.BILLING.NAME,
    target: GITHUB_LINK.BILLING.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: GITHUB_LINK.STATUS.NAME,
    target: GITHUB_LINK.STATUS.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: 'VB - NPM Packages (prettydamntired)',
    target: 'https://www.npmjs.com/settings/prettydamntired/packages',
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: FLYIO_LINK.DASHBOARD.NAME,
    target: FLYIO_LINK.DASHBOARD.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: FLYIO_LINK.BILLING.NAME,
    target: FLYIO_LINK.BILLING.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: FLYIO_LINK.DOCS.NAME,
    target: FLYIO_LINK.DOCS.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: 'AWS Free Tier',
    target: 'https://aws.amazon.com/free/',
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: 'VB - Cloudflare Billing',
    target: 'https://dash.cloudflare.com/26d066ec62c4d27b8da5e9aebac17293/billing',
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: 'VB - Cloudflare Domains',
    target: 'https://dash.cloudflare.com/26d066ec62c4d27b8da5e9aebac17293/registrar/domains',
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: 'VB - Cloudflare Workers',
    target: 'https://dash.cloudflare.com/26d066ec62c4d27b8da5e9aebac17293/workers-and-pages',
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: 'Cloudflare R2 Pricing',
    target: 'https://developers.cloudflare.com/r2/pricing/',
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: 'VB - Cloudflare R2 Buckets',
    target: 'https://dash.cloudflare.com/26d066ec62c4d27b8da5e9aebac17293/r2/overview',
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: CLOUDFLARE_LINK.DNS_DOCS.NAME,
    target: CLOUDFLARE_LINK.DNS_DOCS.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: CLOUDFLARE_LINK.PAGES_DOCS.NAME,
    target: CLOUDFLARE_LINK.PAGES_DOCS.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: CLOUDFLARE_LINK.WORKERS_DOCS.NAME,
    target: CLOUDFLARE_LINK.WORKERS_DOCS.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: CLOUDFLARE_LINK.R2_STORAGE_DOCS.NAME,
    target: CLOUDFLARE_LINK.R2_STORAGE_DOCS.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: CLOUDFLARE_LINK.TURNSTILE_DOCS.NAME,
    target: CLOUDFLARE_LINK.TURNSTILE_DOCS.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: 'OpenWeather API',
    target: 'https://openweathermap.org/api',
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: 'OpenWeather Pricing',
    target: 'https://openweathermap.org/price',
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: 'OpenWeather City Search',
    target: 'https://openweathermap.org/find',
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: 'MongoDB Console',
    target: 'https://cloud.mongodb.com/v2/',
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: GOOGLE_SERVICES.ADSENSE.NAME,
    target: GOOGLE_SERVICES.ADSENSE.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: GOOGLE_SERVICES.ANALYTICS.NAME,
    target: GOOGLE_SERVICES.ANALYTICS.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: OPENAI_LINK.BILLING.NAME,
    target: OPENAI_LINK.BILLING.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: OPENAI_LINK.DOCS.NAME,
    target: OPENAI_LINK.DOCS.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: TWILIO_LINK.BILLING.NAME,
    target: TWILIO_LINK.BILLING.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: TWILIO_LINK.PHONE_NUMBERS.NAME,
    target: TWILIO_LINK.PHONE_NUMBERS.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: TWILIO_LINK.DOCS.NAME,
    target: TWILIO_LINK.DOCS.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: CLAUDE_LINK.CODE.NAME,
    target: CLAUDE_LINK.CODE.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: GCP_LINK.DASHBOARD.NAME,
    target: GCP_LINK.DASHBOARD.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: GCP_LINK.STATUS.NAME,
    target: GCP_LINK.STATUS.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: OPENWEATHER_LINK.DASHBOARD.NAME,
    target: OPENWEATHER_LINK.DASHBOARD.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: OPENWEATHER_LINK.BILLING.NAME,
    target: OPENWEATHER_LINK.BILLING.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: OPENWEATHER_LINK.PAYMENT_HISTORY.NAME,
    target: OPENWEATHER_LINK.PAYMENT_HISTORY.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: OPENWEATHER_LINK.STATUS.NAME,
    target: OPENWEATHER_LINK.STATUS.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: TERRAFORM_LINK.DASHBOARD.NAME,
    target: TERRAFORM_LINK.DASHBOARD.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: TERRAFORM_LINK.BILLING.NAME,
    target: TERRAFORM_LINK.BILLING.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: TERRAFORM_LINK.USAGE.NAME,
    target: TERRAFORM_LINK.USAGE.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: TERRAFORM_LINK.STATUS.NAME,
    target: TERRAFORM_LINK.STATUS.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: ROBOFLOW_LINK.DASHBOARD.NAME,
    target: ROBOFLOW_LINK.DASHBOARD.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: ROBOFLOW_LINK.BILLING.NAME,
    target: ROBOFLOW_LINK.BILLING.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: ROBOFLOW_LINK.USAGE.NAME,
    target: ROBOFLOW_LINK.USAGE.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: DEEPSEEK_LINK.DASHBOARD.NAME,
    target: DEEPSEEK_LINK.DASHBOARD.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: DEEPSEEK_LINK.BILLING.NAME,
    target: DEEPSEEK_LINK.BILLING.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: DEEPSEEK_LINK.USAGE.NAME,
    target: DEEPSEEK_LINK.USAGE.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: GROK_LINK.DASHBOARD.NAME,
    target: GROK_LINK.DASHBOARD.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: GEMINI_LINK.DASHBOARD.NAME,
    target: GEMINI_LINK.DASHBOARD.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: GEMINI_LINK.BILLING.NAME,
    target: GEMINI_LINK.BILLING.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: GEMINI_LINK.USAGE.NAME,
    target: GEMINI_LINK.USAGE.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: ANTHROPIC_LINK.DASHBOARD.NAME,
    target: ANTHROPIC_LINK.DASHBOARD.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: ANTHROPIC_LINK.BILLING.NAME,
    target: ANTHROPIC_LINK.BILLING.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: ANTHROPIC_LINK.USAGE.NAME,
    target: ANTHROPIC_LINK.USAGE.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: STRIPE_LINK.DASHBOARD.NAME,
    target: STRIPE_LINK.DASHBOARD.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: STRIPE_LINK.BILLING.NAME,
    target: STRIPE_LINK.BILLING.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: STRIPE_LINK.USAGE.NAME,
    target: STRIPE_LINK.USAGE.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: STRIPE_LINK.API_MANAGEMENT.NAME,
    target: STRIPE_LINK.API_MANAGEMENT.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
  {
    label: STRIPE_LINK.STATUS.NAME,
    target: STRIPE_LINK.STATUS.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.DEV,
  },
];

const VB_LINKS = [
  {
    label: 'VB - NPM Packages',
    target: 'https://www.npmjs.com/settings/vigilant-broccoli/packages',
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.VIGILANT_BROCCOLI,
  },
  {
    label: 'VB - GitHub Repo',
    target: 'https://github.com/iamharryliu/vigilant-broccoli',
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.VIGILANT_BROCCOLI,
  },
  {
    label: 'VB - GitHub Actions',
    target: 'https://github.com/iamharryliu/vigilant-broccoli/actions',
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.VIGILANT_BROCCOLI,
  },
  {
    label: 'VB - GCP API Credentials',
    target:
      'https://console.cloud.google.com/apis/credentials?project=vigilant-broccoli',
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.VIGILANT_BROCCOLI,
  },
];

const UTILITY_LINKS = [
  {
    label: MAC_OS_APP.SLACK.NAME,
    target: MAC_OS_APP.SLACK.NAME,
    type: OPEN_TYPE.MAC_APPLICATION,
    subgroup: LINK_GROUP_SUBGROUP.UTILITY,
  },
  {
    label: GOOGLE_SERVICES.GMAIL.NAME,
    target: GOOGLE_SERVICES.GMAIL.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.UTILITY,
  },
  {
    label: GOOGLE_SERVICES.GMAIL.FILTERS.NAME,
    target: GOOGLE_SERVICES.GMAIL.FILTERS.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.UTILITY,
  },
  {
    label: GOOGLE_SERVICES.CALENDAR.NAME,
    target: GOOGLE_SERVICES.CALENDAR.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.UTILITY,
  },
  {
    label: GOOGLE_SERVICES.MEET.NAME,
    target: GOOGLE_SERVICES.MEET.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.UTILITY,
  },
  {
    label: UTILITY_URL.AMAZON.NAME,
    target: UTILITY_URL.AMAZON.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.UTILITY,
  },
  {
    label: GOOGLE_SERVICES.YOUTUBE.NAME,
    target: GOOGLE_SERVICES.YOUTUBE.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.UTILITY,
  },
  {
    label: UTILITY_URL.PINTEREST.NAME,
    target: UTILITY_URL.PINTEREST.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.UTILITY,
  },
  {
    label: GOOGLE_SERVICES.PHOTOS.NAME,
    target: GOOGLE_SERVICES.PHOTOS.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.UTILITY,
  },
  {
    label: GOOGLE_SERVICES.CONTACTS.NAME,
    target: GOOGLE_SERVICES.CONTACTS.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.UTILITY,
  },
  {
    label: GOOGLE_SERVICES.DRIVE.NAME,
    target: GOOGLE_SERVICES.DRIVE.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.UTILITY,
  },
  {
    label: GOOGLE_SERVICES.KEEP.NAME,
    target: GOOGLE_SERVICES.KEEP.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.UTILITY,
  },
  {
    label: GOOGLE_SERVICES.TASKS.NAME,
    target: GOOGLE_SERVICES.TASKS.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.UTILITY,
  },
  {
    label: GOOGLE_SERVICES.MAPS.NAME,
    target: GOOGLE_SERVICES.MAPS.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.UTILITY,
  },
  {
    label: GOOGLE_SERVICES.TRANSLATE.NAME,
    target: GOOGLE_SERVICES.TRANSLATE.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.UTILITY,
  },
  {
    label: 'OpenL Bulk Translator',
    target: 'https://openl.io/bulk-translator',
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.UTILITY,
  },
  {
    label: OPENAI_LINK.CHATGPT.NAME,
    target: OPENAI_LINK.CHATGPT.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.UTILITY,
  },
  {
    label: OPENAI_LINK.INCOGNITO.NAME,
    target: OPENAI_LINK.INCOGNITO.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.UTILITY,
  },
  {
    label: CLAUDE_LINK.CLAUDE.NAME,
    target: CLAUDE_LINK.CLAUDE.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.UTILITY,
  },
  {
    label: CLAUDE_LINK.INCOGNITO.NAME,
    target: CLAUDE_LINK.INCOGNITO.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.UTILITY,
  },
  {
    label: CLAUDE_LINK.PRICING.NAME,
    target: CLAUDE_LINK.PRICING.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.UTILITY,
  },
  {
    label: GOOGLE_SERVICES.GEMINI.NAME,
    target: GOOGLE_SERVICES.GEMINI.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.UTILITY,
  },
  {
    label: GROK_LINK.GROK.NAME,
    target: GROK_LINK.GROK.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.UTILITY,
  },
  {
    label: UTILITY_URL.FIND_MY.NAME,
    target: UTILITY_URL.FIND_MY.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.UTILITY,
  },
];

const CAREER_LINKS = [
  {
    label: PERSONAL_URL.RESUME.NAME,
    target: PERSONAL_URL.RESUME.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.CAREER,
  },
  {
    label: 'LinkedIn',
    target: 'https://www.linkedin.com',
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.CAREER,
  },
];

const LEISURE_LINKS = [
  {
    label: MAC_OS_APP.SPOTIFY.NAME,
    target: MAC_OS_APP.SPOTIFY.NAME,
    type: OPEN_TYPE.MAC_APPLICATION,
    subgroup: LINK_GROUP_SUBGROUP.LEISURE,
  },
  {
    label: 'Manga',
    target: ' https://ww2.mangafreak.me/',
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.LEISURE,
  },
  {
    label: PERSONAL_URL.TO_DRAW.NAME,
    target: PERSONAL_URL.TO_DRAW.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.LEISURE,
  },
  {
    label: PERSONAL_URL.TO_READ.NAME,
    target: PERSONAL_URL.TO_READ.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.LEISURE,
  },
  {
    label: PERSONAL_URL.TO_WATCH_ANIME.NAME,
    target: PERSONAL_URL.TO_WATCH_ANIME.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.LEISURE,
  },
  {
    label: PERSONAL_URL.TO_WATCH_MOVIES_SHOWS.NAME,
    target: PERSONAL_URL.TO_WATCH_MOVIES_SHOWS.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.LEISURE,
  },
];

const LEARN_LINKS = [
  {
    label: 'Udemy',
    target: 'https://www.udemy.com/',
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.LEARN,
  },
  {
    label: 'Memrise',
    target: 'https://app.memrise.com/dashboard',
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.LEARN,
  },
  {
    label: 'Memrise (Community Version)',
    target: 'https://community-courses.memrise.com/dashboard',
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.LEARN,
  },
];

const FOR_LATER_LINKS = [
  {
    label: 'TODO(Journal)',
    target: JOURNAL_PATH.TODO,
    type: OPEN_TYPE.VSCODE,
    subgroup: LINK_GROUP_SUBGROUP.FOR_LATER,
  },
  {
    label: 'TODO(vigilant-broccoli)',
    target: VB_REPO_PATH.TODO,
    type: OPEN_TYPE.VSCODE,
    subgroup: LINK_GROUP_SUBGROUP.FOR_LATER,
  },
  {
    label: GOOGLE_SERVICES.YOUTUBE.WATCH_LATER.NAME,
    target: GOOGLE_SERVICES.YOUTUBE.WATCH_LATER.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.FOR_LATER,
  },
  {
    label: PERSONAL_URL.INSTAGRAM_SAVED.NAME,
    target: PERSONAL_URL.INSTAGRAM_SAVED.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.FOR_LATER,
  },
  {
    label: PERSONAL_URL.REDDIT_SAVED.NAME,
    target: PERSONAL_URL.REDDIT_SAVED.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.FOR_LATER,
  },
  {
    label: 'Expiration',
    target: JOURNAL_PATH.EXPIRATION,
    type: OPEN_TYPE.VSCODE,
    subgroup: LINK_GROUP_SUBGROUP.FOR_LATER,
  },
];

const HOME_LINKS = [
  {
    label: 'Food',
    target: JOURNAL_PATH.FOOD,
    type: OPEN_TYPE.VSCODE,
    subgroup: LINK_GROUP_SUBGROUP.HOME,
  },
  {
    label: PERSONAL_URL.GROCERIES.NAME,
    target: PERSONAL_URL.GROCERIES.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.HOME,
  },
  {
    label: PERSONAL_URL.HOME_PROJECTS.NAME,
    target: PERSONAL_URL.HOME_PROJECTS.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.HOME,
  },
  {
    label: PERSONAL_URL.HOME_KITCHEN_INVENTORY.NAME,
    target: PERSONAL_URL.HOME_KITCHEN_INVENTORY.URL,
    type: OPEN_TYPE.BROWSER,
    subgroup: LINK_GROUP_SUBGROUP.HOME,
  },
];

export const QUICK_LINKS = [
  ...VB_LINKS,
  ...DEV_LINKS,
  ...UTILITY_LINKS,
  ...CAREER_LINKS,
  ...LEISURE_LINKS,
  ...LEARN_LINKS,
  ...FOR_LATER_LINKS,
  ...HOME_LINKS,
];
