# fly.toml app configuration file generated for consumer-holy-tree-7737 on 2025-02-07T01:10:02+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'consumer-holy-tree-7737'
primary_region = 'arn'

[build]

[[vm]]
  size = 'shared-cpu-1x'
