alias opengmail='open -a "Google Chrome" "https://gmail.com/"'
alias openyoutube='open -a "Google Chrome" "https://www.youtube.com/"'
alias openudemy='open -a "Google Chrome" "https://www.udemy.com/"'
alias openmemrise='open -a "Google Chrome" "https://app.memrise.com/dashboard"'
alias openamazon='open -a "Google Chrome" "https://www.amazon.ca/"'
alias openchatgpt='open -a "Google Chrome" "https://chat.openai.com/"'
alias google="~/shell-scripts/google_search.sh"
alias youtube="~/shell-scripts/youtube_search.sh"
alias amazon="~/shell-scripts/amazon_search.sh"
