name: backup-vb-repo

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  backup-vb-repo:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          create_credentials_file: false

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Upload backup to GCS
        run: |
          TIMESTAMP=$(date -u +%Y-%m-%d)
          curl -sL -o vigilant-broccoli.zip https://github.com/iamharryliu/vigilant-broccoli/archive/refs/heads/main.zip
          gsutil cp vigilant-broccoli.zip gs://vigilant-broccoli-backup/vigilant-broccoli-backup-$TIMESTAMP.zip
