name: ci-pr-check

on:
  pull_request:
    branches: ['main']

permissions:
  contents: read

concurrency:
  group: ci-pr-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nx-affected:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-nx-workspace

      - name: Lint, test, build affected
        working-directory: ./projects/nx-workspace
        run: pnpm exec nx affected -t lint test build --base=$NX_BASE --head=$NX_HEAD

  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: '3.13'

      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        env:
          SKIP: grind-75-tests,lint-staged
