name: ci-pr-check

on:
  pull_request:
    branches: ['main']

permissions:
  contents: read

concurrency:
  group: ci-pr-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nx-affected:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-nx-workspace

      - name: Lint, test, build affected
        working-directory: ./projects/nx-workspace
        run: pnpm exec nx affected -t lint test build --base=$NX_BASE --head=$NX_HEAD

  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.13'

      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        env:
          SKIP: grind-75-tests,lint-staged
