name: Deploy Cloud8Skate (Angular)
on:
  push: { branches: ['main'] }

jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: production
    defaults:
      run:
        working-directory: ./projects/nx-workspace
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npx nx build cloud-8-skate-angular
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: projects/nx-workspace
          command: pages deploy dist/apps/ui/cloud-8-skate-angular/browser --project-name cloud-8-skate-angular
