name: cron-upptime

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [uptime]

permissions:
  contents: write
  issues: write

concurrency:
  group: upptime
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: upptime/uptime-monitor@1e27390f41da4d644dd921eed19fee111bdf5c88 # v1.43.8
        env:
          GH_PAT: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
