name: cron-utility-backup-journal

on:
  push:
    paths:
      - .github/workflows/cron-utility-backup-journal.yml
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  backup-journal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Import Secrets from Vault
        uses: ./.github/actions/vault-secrets
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          secrets: |
            kv/data/secrets GITEA_TOKEN | GITEA_TOKEN ;

      - name: Upload backup to GCS
        run: |
          TIMESTAMP=$(date -u +%Y-%m-%d)
          curl -sL -H "Authorization: token ${{ secrets.GITEA_TOKEN }}" \
            -o journal.zip \
            https://git.harryliu.dev/api/v1/repos/prettydamntired/journal/archive/main.zip
          gsutil cp journal.zip gs://vigilant-broccoli-backup/journal-backup-$TIMESTAMP.zip

      - name: Cleanup old backups
        run: |
          MAX_BACKUPS=7
          BACKUPS=$(gsutil ls gs://vigilant-broccoli-backup/journal-backup-*.zip | sort)
          BACKUP_COUNT=$(echo "$BACKUPS" | wc -l)
          if [ "$BACKUP_COUNT" -gt "$MAX_BACKUPS" ]; then
            DELETE_COUNT=$((BACKUP_COUNT - MAX_BACKUPS))
            echo "$BACKUPS" | head -n "$DELETE_COUNT" | xargs gsutil rm
          fi
