name: Save vigilant-broccoli

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  upload-resume:
    runs-on: ubuntu-latest
    environment:
      name: production
    defaults:
      run:
        working-directory: ./scripts/node
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Decode service account key
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}" | base64 -d > service-account.json
      - name: Run script.
        run: npx tsx download-vb.ts
