name: Deploy React Demo
on:
  push: { branches: ['main'] }

jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: production
    defaults:
      run:
        working-directory: ./projects/nx-workspace
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - name: Build App
        run: npx nx build react-tools
      - name: Deploy App
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: projects/demo-apps/react-demo
          command: pages deploy dist dist/apps/ui/react-tools --project-name react-demo
