name: Deploy Nx Apps
on:
  push: { branches: ['main'] }

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLYIO_AUTH_TOKEN }}
      MONGO_DB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
      MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_TWILIO_AUTH_TOKEN }}
    environment:
      name: production
    defaults:
      run:
        working-directory: ./projects/nx-workspace
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      # TODO: figure out how to get e2e to pass
      # - run: npx nx affected -t lint test build e2e-ci deploy
      # - run: npx nx affected -t lint test build deploy
