name: Deploy harryliu.design Angular - Deploy App
on:
  push: { branches: ['main'] }
  # Handles CMS Updates
  schedule: [{ cron: '*/15 * * * *' }]

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: production
    defaults:
      run:
        working-directory: ./projects/nx-workspace
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - name: Build harryliu-design-ui
        run: npx nx build personal-website-frontend
      - name: Deploy harryliu-design-ui
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: projects/nx-workspace
          command: pages deploy dist/apps/ui/personal-website-frontend/browser --project-name harryliu-design-angular
