name: deploy-docs-md

on:
  push:
    branches: [main]
    paths:
      - notes/**
      - .github/workflows/deploy-docs-md.yml
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy-docs-md
  cancel-in-progress: false

jobs:
  deploy-docs-md:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: ./.github/actions/setup-nx-workspace

      - name: Import Secrets from Vault
        uses: ./.github/actions/vault-secrets
        with:
          gcp_workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          gcp_service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          secrets: |
            kv/data/secrets CLOUDFLARE_ACCOUNT_ID | CLOUDFLARE_ACCOUNT_ID ;
            kv/data/secrets CLOUDFLARE_API_TOKEN_VB_DEPLOY_NX_APPS | CLOUDFLARE_API_TOKEN ;

      - name: Deploy to Cloudflare Pages
        working-directory: ./projects/nx-workspace
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ env.CLOUDFLARE_API_TOKEN }}
        run: pnpm exec nx run docs-md:deploy --skip-nx-cache
