name: Deploy Toronto Alerts (Flask)
on:
  push: { branches: ['main'] }

jobs:
  main:
    if: ${{ !startsWith(github.event.head_commit.message, 'docs') }}
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLYIO_AUTH_TOKEN }}
    environment:
      name: production
    defaults:
      run:
        working-directory: ./projects/toronto-alerts/toronto-alerts-flask
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --ha=false --dockerfile Dockerfile --config fly.toml
