name: Toronto Alerts - Email Subscribers

on:
  schedule: [{ cron: '*/5 * * * *' }]

jobs:
  run_script:
    runs-on: ubuntu-latest
    environment:
      name: production
    defaults:
      run:
        working-directory: ./projects/toronto-alerts/scripts
    steps:
      - name: Checkout code.
        uses: actions/checkout@v2

      - name: Set up Python.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies.
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script.
        env:
          GTA_UPDATE_ALERT_EMAIL: ${{ secrets.GTA_UPDATE_ALERT_EMAIL }}
          GTA_UPDATE_ALERT_EMAIL_PASSWORD: ${{ secrets.GTA_UPDATE_ALERT_EMAIL_PASSWORD }}
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        run: python email_subscribers.py 10
