name: GTA Update Alert

on:
  push: { branches: ['main'] }
  schedule: [{ cron: '0 */1 * * *' }]

jobs:
  run_script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts/python/gta_update
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python script
        run: python gta_update.py
        env:
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
          MY_EMAIL_PASSWORD: ${{ secrets.MY_EMAIL_PASSWORD }}
      - run: 'echo "$SSH_KEY" > key'
        shell: bash
        env:
          SSH_KEY: ${{secrets.MY_EMAIL_PASSWORD}}
