name: CI
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

env:
  FLY_API_TOKEN: ${{ secrets.HARRYLIU_DESIGN_EXPRESS_FLY_API_TOKEN }}
  MONGO_DB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
  MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: production
    defaults:
      run:
        working-directory: ./projects/nx-workspace
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      # - run: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="e2e-ci"
      - run: npm ci
      - uses: nrwl/nx-set-shas@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      # - run: git branch --track main origin/main
      # - run: npx nx-cloud record -- nx format:check
      # - run: npx nx pre-build personal-website-frontend
      - run: npx nx run-many --target=build --all
      - run: npx nx deploy personal-website-backend
      # - run: npx nx affected -t lint test build e2e-ci
